version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ../:/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --reload

  postgresql:
    image: postgres:15.2-alpine3.17
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./sgbd:/var/lib/postgresql/data